package com.hx.kp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2020-08-12T15:29:15.216+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", name = "bmpService")
@XmlSeeAlso({ObjectFactory.class})
public interface BmpService {

    @WebMethod
    @RequestWrapper(localName = "receiveProjectInfo", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveProjectInfo")
    @ResponseWrapper(localName = "receiveProjectInfoResponse", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveProjectInfoResponse")
    @WebResult(name = "projectMsg", targetNamespace = "")
    public String receiveProjectInfo(
        @WebParam(name = "ET_PROJ", targetNamespace = "")
        java.util.List<EtProj> etPROJ,
        @WebParam(name = "ES_MSG_HEAD", targetNamespace = "")
        EsMsgHead esMSGHEAD
    );

    @WebMethod
    @RequestWrapper(localName = "receiveAuditFeedbackInfo", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveAuditFeedbackInfo")
    @ResponseWrapper(localName = "receiveAuditFeedbackInfoResponse", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveAuditFeedbackInfoResponse")
    @WebResult(name = "auditFeedbackMsg", targetNamespace = "")
    public ResAuditFeedback receiveAuditFeedbackInfo(
        @WebParam(name = "EV_XML_SIZE", targetNamespace = "")
        String evXMLSIZE,
        @WebParam(name = "EV_RESERVE1", targetNamespace = "")
        String evRESERVE1,
        @WebParam(name = "EV_RESERVE2", targetNamespace = "")
        String evRESERVE2,
        @WebParam(name = "ET_RETURN", targetNamespace = "")
        java.util.List<EtReturn> etRETURN
    );

    @WebMethod
    @RequestWrapper(localName = "receiveAuditInfo", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveAuditInfo")
    @ResponseWrapper(localName = "receiveAuditInfoResponse", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveAuditInfoResponse")
    @WebResult(name = "auditMsg", targetNamespace = "")
    public ResAudit receiveAuditInfo(
        @WebParam(name = "IV_SIZE", targetNamespace = "")
        String ivSIZE,
        @WebParam(name = "IV_LOGSYS", targetNamespace = "")
        String ivLOGSYS,
        @WebParam(name = "IV_RESERVE1", targetNamespace = "")
        String ivRESERVE1,
        @WebParam(name = "IV_RESERVE2", targetNamespace = "")
        String ivRESERVE2,
        @WebParam(name = "IV_RESERVE3", targetNamespace = "")
        String ivRESERVE3,
        @WebParam(name = "IT_XML", targetNamespace = "")
        java.util.List<ItXml> itXML,
        @WebParam(name = "IT_APNUM", targetNamespace = "")
        java.util.List<ItApnum> itAPNUM,
        @WebParam(name = "SYWTY", targetNamespace = "")
        String sywty
    );

    @WebMethod
    @RequestWrapper(localName = "receiveDeptInfo", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveDeptInfo")
    @ResponseWrapper(localName = "receiveDeptInfoResponse", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveDeptInfoResponse")
    @WebResult(name = "deptMsg", targetNamespace = "")
    public String receiveDeptInfo(
        @WebParam(name = "IT_DEPT", targetNamespace = "")
        java.util.List<ItDept> itDEPT,
        @WebParam(name = "ES_MSG_HEAD", targetNamespace = "")
        EsMsgHead esMSGHEAD
    );

    @WebMethod
    @RequestWrapper(localName = "receiveUserFeedbackInfo", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveUserFeedbackInfo")
    @ResponseWrapper(localName = "receiveUserFeedbackInfoResponse", targetNamespace = "http://api.ws.common.adminWeb.bmp.seg/", className = "com.hx.kp.ReceiveUserFeedbackInfoResponse")
    @WebResult(name = "userMsg", targetNamespace = "")
    public String receiveUserFeedbackInfo(
        @WebParam(name = "IS_MSG_HEAD", targetNamespace = "")
        IsMsgHead isMSGHEAD,
        @WebParam(name = "IS_RESP", targetNamespace = "")
        java.util.List<IsResp> isRESP
    );
}
