
package com.hx.kp;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.alibaba.fastjson.JSON;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2020-08-12T15:29:15.162+08:00
 * Generated source version: 3.2.6
 *
 */
public final class BmpService_BmpServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://api.ws.common.adminWeb.bmp.seg/", "bmpService");

    private BmpService_BmpServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {

      // 调用WebService
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setServiceClass(BmpService.class);
        factory.setAddress("http://localhost:8080/services/bmpService?wsdl");
        BmpService service = (BmpService) factory.create();
        java.util.List<ItXml> _receiveAuditInfo_itXML = new ArrayList<>();
        ItXml itXml = new ItXml();
        itXml.setXDATA("sdsdsd");
        _receiveAuditInfo_itXML.add(itXml);
        java.util.List<ItApnum> _receiveAuditInfo_itAPNUM = new ArrayList<>();
        ItApnum itApnum = new ItApnum();
        itApnum.setAPNUM("asafsaf");
        _receiveAuditInfo_itAPNUM.add(itApnum);

        ResAudit asasss = service.receiveAuditInfo("k", "k", "k", "k", "k", _receiveAuditInfo_itXML, _receiveAuditInfo_itAPNUM, "GA01");

        System.out.println("JSON >>> " + JSON.toJSONString(asasss));

//        URL wsdlURL = BmpService_Service.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//
//        BmpService_Service ss = new BmpService_Service(wsdlURL, SERVICE_NAME);
//        BmpService port = ss.getBmpServiceImplPort();
//
//        {
//        System.out.println("Invoking receiveProjectInfo...");
//        java.util.List<EtProj> _receiveProjectInfo_etPROJ = null;
//        EsMsgHead _receiveProjectInfo_esMSGHEAD = null;
//        String _receiveProjectInfo__return = port.receiveProjectInfo(_receiveProjectInfo_etPROJ, _receiveProjectInfo_esMSGHEAD);
//        System.out.println("receiveProjectInfo.result=" + _receiveProjectInfo__return);
//
//
//        }
//        {
//        System.out.println("Invoking receiveAuditFeedbackInfo...");
//        String _receiveAuditFeedbackInfo_evXMLSIZE = "";
//        String _receiveAuditFeedbackInfo_evRESERVE1 = "";
//        String _receiveAuditFeedbackInfo_evRESERVE2 = "";
//        java.util.List<EtReturn> _receiveAuditFeedbackInfo_etRETURN = null;
//        ResAuditFeedback _receiveAuditFeedbackInfo__return = port.receiveAuditFeedbackInfo(_receiveAuditFeedbackInfo_evXMLSIZE, _receiveAuditFeedbackInfo_evRESERVE1, _receiveAuditFeedbackInfo_evRESERVE2, _receiveAuditFeedbackInfo_etRETURN);
//        System.out.println("receiveAuditFeedbackInfo.result=" + _receiveAuditFeedbackInfo__return);
//
//
//        }
//        {
//        System.out.println("Invoking receiveAuditInfo...");
//        String _receiveAuditInfo_ivSIZE = "";
//        String _receiveAuditInfo_ivLOGSYS = "";
//        String _receiveAuditInfo_ivRESERVE1 = "";
//        String _receiveAuditInfo_ivRESERVE2 = "";
//        String _receiveAuditInfo_ivRESERVE3 = "";
//        java.util.List<ItXml> _receiveAuditInfo_itXML = null;
//        java.util.List<ItApnum> _receiveAuditInfo_itAPNUM = null;
//        String _receiveAuditInfo_sywty = "";
//        ResAudit _receiveAuditInfo__return = port.receiveAuditInfo(_receiveAuditInfo_ivSIZE, _receiveAuditInfo_ivLOGSYS, _receiveAuditInfo_ivRESERVE1, _receiveAuditInfo_ivRESERVE2, _receiveAuditInfo_ivRESERVE3, _receiveAuditInfo_itXML, _receiveAuditInfo_itAPNUM, _receiveAuditInfo_sywty);
//        System.out.println("receiveAuditInfo.result=" + _receiveAuditInfo__return);
//
//
//        }
//        {
//        System.out.println("Invoking receiveDeptInfo...");
//        java.util.List<ItDept> _receiveDeptInfo_itDEPT = null;
//        EsMsgHead _receiveDeptInfo_esMSGHEAD = null;
//        String _receiveDeptInfo__return = port.receiveDeptInfo(_receiveDeptInfo_itDEPT, _receiveDeptInfo_esMSGHEAD);
//        System.out.println("receiveDeptInfo.result=" + _receiveDeptInfo__return);
//
//
//        }
//        {
//        System.out.println("Invoking receiveUserFeedbackInfo...");
//        IsMsgHead _receiveUserFeedbackInfo_isMSGHEAD = null;
//        java.util.List<IsResp> _receiveUserFeedbackInfo_isRESP = null;
//        String _receiveUserFeedbackInfo__return = port.receiveUserFeedbackInfo(_receiveUserFeedbackInfo_isMSGHEAD, _receiveUserFeedbackInfo_isRESP);
//        System.out.println("receiveUserFeedbackInfo.result=" + _receiveUserFeedbackInfo__return);
//
//
//        }
//
//        System.exit(0);
    }

}
