#
#spring:
#  datasource: #数据库 配置
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&failOverReadOnly=false&autoReconnect=true
#    name: dataSource
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    type: com.zaxxer.hikari.HikariDataSource
##    hikari:
##      minimum-idle: 13
##      maximum-pool-size: 15
##      idle-timeout: 30000
##      pool-name: HikariCP
##      max-lifetime: 1800000
##      connection-timeout: 3000
##      connection-test-query: SELECT 1
#
#  mybatis-plus:
#    mapper-locations: classpath:/mapper/*Mapper.xml
#    type-aliases-package: qhy.example.bean.job
#    global-config:
#      db-config:
#        id-type: auto
#        field-strategy: not_empty
#        #驼峰下划线转换
#        column-underline: true
#        #逻辑删除配置
#        logic-delete-value: 0
#        logic-not-delete-value: 1
#        db-type: mysql
#      refresh: false
#      configuration:
#        map-underscore-to-camel-case: true
#        cache-enabled: false